### ISSUE TITLE
About your example for predicting 

### ISSUE THREAD

**Issue by WxZy530** [why2011btv/JCL_EMNLP20#1]
Hi,I am still following your nice work.
It's happy to find that you give some easy examples for predicting the relations,there are 2 questions that bothers:

- 1.I tried this commd to test the example/input.json by "python predict.py example/input_data.json subevent Joint 
predict.json",raise:
Traceback (most recent call last):
  File "/home/wangxiao/New_Folder/JCL_EMNLP20/document_reader.py", line 160, in subword_id_getter_space_split
    subword_id = start_char_to_subword_id[e_start_char]
KeyError: 164
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "predict.py", line 53, in <module>
    y_sent, y_position = subword_id_getter_space_split(an_instance["sent_2"], an_instance["e2_start_char"])
  File "/home/wangxiao/New_Folder/JCL_EMNLP20/document_reader.py", line 163, in subword_id_getter_space_split
    raise Exception('The provided event start char is wrong')  

- 2.The input file for your predict.py is two sentences, what if I need to extract relations from a document? Is this the right way that I split the document into sentences, and create a json file likes:"{sent1,e1,sent2,e2},{sent1,e1,sent3,e3}...{sent2,e2,sent3,e3}...{sent n-1,e n-1,sent n,e n}"?I am worry about whether the cross sentence event pairs can be predict or not?

Hopes for your attention,thanks.

**Comment by why2011btv** [comment]
1. Please refer to the instruction in [README](https://github.com/why2011btv/JCL_EMNLP20#command-for-predicting-temporal-relations). There are some errors in the input_data.json and I have deleted it. Both [subevent_example_input.json](https://github.com/why2011btv/JCL_EMNLP20/blob/main/example/subevent_example_input.json) and [temporal_example_input.json](https://github.com/why2011btv/JCL_EMNLP20/blob/main/example/temporal_example_input.json) are correct input files for prediction.

2. Regarding prediction for event relations in a document, you can perform pairwise predictions for each pair of events, just as what you described. The learned constraints should guarantee that there are no contradictory results. The two input sentences can be either the same or different sentences. You only need to indicate the start character id of the events in the input file: "{sent1, e1_start_char, sent2, e2_start_char}, {sent1, e1_start_char, sent3, e3_start_char} ..."
